### ISSUE TITLE
Error while compiling tutorial files

### ISSUE THREAD

**Issue by arthuber** [aeantipov/pomerol#1]
Hello,

i get an error while trying to compile the tutorial. The error massage is:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
pomerol_DEP_LIBRARIES

regards
Arthur

**Comment by aeantipov** [comment]
Arthur, is this bug still present? 
If so, can you please copy me error messages and configuration files you use? 
Check for CMakeError.log and CMakeOutput.log in build_directory/CMakeFiles.

**Comment by arthuber** [comment]
Yes the bug is still present. I send you the files via email. Thanks.

**Comment by aeantipov** [comment]
It looks like the overhaul of pomerol CMake should have fixed that, at least the automated builds pass. Closing it.
