### ISSUE TITLE
Computing two-particle GF in imaginary time

### ISSUE THREAD

**Issue by shinaoka** [aeantipov/pomerol#15]
Hi, we've found that it's very expensive to compute two-particle GF in Matsubara frequencies especially for a seven-orbital model.
The reason is obvious: pomerol first makes a list of terms by performing summation over all intermediate states, whose computational complexity may scale as O(N^4) (N is the dimension of the Hilbert space).
Instead, one could compute G(tau1, tau2, tau3, tau4) for a given (tau1, tau2, tau3, tau4), in which summation over intermediate states is no more necessary.
Is there any attempt to implement the computation of two-particle GF in imaginary time?

**Comment by aeantipov** [comment]
Hiroshi, I agree - computing in tau might be more efficient if you only need one combination of times. We haven't done it. What might help is that every TwoParticicleGFPart is associated with a fixed permutation of operators, which is what you need in this case.

**Comment by shinaoka** [comment]
Anyway, we have figured out how to deal with Matsubara-domain data efficiently.
There is no urgent need for us to compute two-particle GF in imaginary-time domain for the moment.
