### ISSUE TITLE
Susceptibility

### ISSUE THREAD

**Issue by j-otsuki** [aeantipov/pomerol#23]
Dear Andrey,

Let me ask one question. Is there any way to compute the susceptibility defined by

    chi(iw) = F < A(tau) B >

where iw is the bosonic Matsubara frequency, and F denotes the Fourier transform from tau to iw. More explicitly, what I want to compute is

    chi_{ijkl}(iw) = F < c_i^+(tau) c_j(tau) c_k^+ c_l >

Best,
Junya

**Comment by aeantipov** [comment]
Dear Junya, 

Unfortunately we haven't implemented anything in Pomerol outside of single- and two- particle Green's functions. There are arbitrary operators available in Pomerol, and by replacing Creation and AnnihilationOperator in Green's function one can do it, but that requires some development and testing. 

Of course in your case if you only need this susceptibility once and for small enough system - get a full twoparticleGF and make a sum. The notation for the frequencies is here https://github.com/aeantipov/pomerol/blob/master/doc/gamma4.pdf (it is c_1 c_2 c^+3 c^+4), so by parametrizing `w_3 = w + \Omega`, `\omega_1 = \omega' + \Omega`, `w_2 = \omega'` and `\omega_4 = \omega` and summing over \omega and \omega' you'll get what you want. That's of course a very expensive and unoptimized way of doing things.

**Comment by j-otsuki** [comment]
Thank you for your quick reply, Andrey.

Can you tell me how exactly one can implement it, though, I'm not sure if I can do it. It seems that I copy ``GreenFunction.cpp`` and ``GreenFunctionPart.cpp``, and replace CreationOperator and AnnihilationOparator with some arbitrary operators (or product of c_i and c_j^+). Are there something which I should take care of?

**Comment by j-otsuki** [comment]
Hi, Andrey. I have implemented a susceptibility calculation. Just for your information, I let you know what I did.

I introduced a class named QuadraticOparator, which inherits FieldOperator in a similar manner to CreationOperator and AnnihilationOperator, but contains a product of creation and annihilation operators, c^+ c. Then, I copy GreenFunction.cpp and replace all appearances of CreationOperator and AnnihilationOperator with QuandraticOperator. Finally, I replace fermionic formulas with bosonic ones. It seems working.

**Comment by aeantipov** [comment]
Junya, sorry I missed the previous message. I am glad to know you worked it out and this is indeed the optimal solution. Would you mind contributing it as a PR to pomerol?

**Comment by j-otsuki** [comment]
I'm happy to contribute my implementation as a PR to the original repo. I'm now further working on implementing <c_i^+ c_j>, which is necessary to complete the susceptibility calculation. I'll let you know when those implementations are finished.

**Comment by aeantipov** [comment]
Thanks a lot, Junya!

**Comment by aeantipov** [comment]
Junya, thanks, this is an incredible work.
I noticed the tests are failing now because they try to build a C++98 code (yes, pomerol still supports it). 
I guess by now the entire community has moved on to c++11, so there isn't much need in legacy support. 
I made a test PR where C++11 is now enforced - if that works one can merge the two.

**Comment by j-otsuki** [comment]
Thanks for the patch. I was testing only with gcc 7.

I merged your commit into the PR branch and now Travis CI was passed.

**Comment by aeantipov** [comment]
Great, let me tag the current master as the last one before C++11 and then I'll merge it.

**Comment by aeantipov** [comment]
Now that PR is merged I close this. Once again - thanks a lot!
