### ISSUE TITLE
Problem linking boost_mpi and boost_serialization

### ISSUE THREAD

**Issue by egcpvanloon** [aeantipov/pomerol#27]
Hi,

I'm currently having trouble making pomerol. During make, I get the following errors:

[ 48%] Linking CXX executable FieldOperatorTest
../libpomerol.so: undefined reference to `boost::mpi::detail::packed_archive_recv(int, int, int, boost::mpi::packed_iarchive&, MPI_Status&)'
../libpomerol.so: undefined reference to `boost::mpi::communicator::operator int() const'
../libpomerol.so: undefined reference to `boost::mpi::detail::packed_archive_send(int, int, int, boost::mpi::packed_oarchive const&)'

The most obvious source for errors would be the boost version ( 1.58.0 on this machine). I am trying to install a newer version of boost to see if that helps (but installing boost is slow...). Do you know what the minimal required version of boost is / which version are you usually using? Do you see other obvious things that could be going wrong?

Thanks in advance,

Erik

**Comment by krivenko** [comment]
Hi Erik,

pomerol is known to be buildable with at least [Boost 1.54](https://travis-ci.org/aeantipov/pomerol/jobs/549502214#L1080). Could it be the case that you are trying to use header files and libraries from different versions of Boost?

Igor

**Comment by aeantipov** [comment]
In many distributions boost and boost-mpi are installed separately.  So it might be that the linking flags don't pick -lboost_mpi

**Comment by egcpvanloon** [comment]
I think I've identified the problem. I want to install pomerol and pomerol2triqs. My triqs is based on an anaconda environment to provide an appropriate version of python and python libraries. However, it also provides its own MPI, and it seems that this is the origin of the problems. 
I can make pomerol without problem if I do not load the anaconda environment, but then pomerol2triqs does not work. 

From here on, I expect the problem to be relatively straightforward to solve, I will let you know if I encounter additional problems.

**Comment by egcpvanloon** [comment]
Compiling boost (with boost mpi and boost serialization) using the anaconda environment and the mpicc it provides worked, eventually.

**Comment by krivenko** [comment]
@egcpvanloon It's been a while since this issue was opened. Should we close it now?
