### ISSUE TITLE
Deprecate POMEROL_COMPLEX_MATRIX_ELEMENTS ?

### ISSUE THREAD

**Issue by aeantipov** [aeantipov/pomerol#38]
Perhaps use a template parameter instead and compile both. Or just simply make it complex altogether (any spin-orbit interaction needs it anyway)

**Comment by krivenko** [comment]
`POMEROL_COMPLEX_MATRIX_ELEMENTS` is gone, types of matrices stored in `HamiltonianPart` and `MonomialOperatorPart` are erased by means of `std::shared_ptr<void>` and are automatically switched at runtime to accommodate respective operators.
