### ISSUE TITLE
Move away from travis to github actions?

### ISSUE THREAD

**Issue by aeantipov** [aeantipov/pomerol#39]
Evaluate if that's useful

**Comment by krivenko** [comment]
I've been seeing people doing this recently, but I'd really like to see the actual point besides the hype.

**Comment by aeantipov** [comment]
yeah, that's why I mention it's worth evaluating, I don't suggest any immediate switch. Also worth having as an item for future references. So far one reason in favor is the artifact publishing, which is done in a nice way in github. With source distribution though there isn't much difference.

**Comment by krivenko** [comment]
Fixed by #42.
